# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import nlp_project_pb2 as nlp__project__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in nlp_project_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class nlp_projectStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_trends = channel.unary_unary(
                '/nlp_project/get_trends',
                request_serializer=nlp__project__pb2.get_trends_request.SerializeToString,
                response_deserializer=nlp__project__pb2.trends.FromString,
                _registered_method=True)


class nlp_projectServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_trends(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_nlp_projectServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_trends': grpc.unary_unary_rpc_method_handler(
                    servicer.get_trends,
                    request_deserializer=nlp__project__pb2.get_trends_request.FromString,
                    response_serializer=nlp__project__pb2.trends.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nlp_project', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nlp_project', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class nlp_project(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_trends(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nlp_project/get_trends',
            nlp__project__pb2.get_trends_request.SerializeToString,
            nlp__project__pb2.trends.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
