# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nlp_project.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'nlp_project.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11nlp_project.proto\"Q\n\x12get_trends_request\x12\x14\n\x0c\x63ountry_code\x18\x01 \x01(\t\x12\r\n\x05theme\x18\x02 \x01(\t\x12\x16\n\x0egenerate_audio\x18\x03 \x01(\x08\"W\n\x06trends\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\r\n\x05story\x18\x02 \x01(\t\x12\r\n\x05\x61udio\x18\x03 \x01(\x0c\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x0f\n\x07message\x18\x05 \x01(\t29\n\x0bnlp_project\x12*\n\nget_trends\x12\x13.get_trends_request\x1a\x07.trendsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nlp_project_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GET_TRENDS_REQUEST']._serialized_start=21
  _globals['_GET_TRENDS_REQUEST']._serialized_end=102
  _globals['_TRENDS']._serialized_start=104
  _globals['_TRENDS']._serialized_end=191
  _globals['_NLP_PROJECT']._serialized_start=193
  _globals['_NLP_PROJECT']._serialized_end=250
# @@protoc_insertion_point(module_scope)
